<?php
include_once('../php/util/notifs.php');
if(!isset($_SESSION)){
    echo "<meta http-equiv='refresh' content='0;url=accueil.phtml'>";
    die();
    exit();
} else if(isset($_SESSION) && ($_SESSION['initiatorIsDirector'] == 0 && $_SESSION['initiatorIsManager'] == 0)){
    echo "<meta http-equiv='refresh' content='0;url=accueil.phtml'>";
    die();
    exit();
}
?>
<!DOCTYPE html>
<html lang="fr" data-theme="light">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.31.0/dist/full.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="../loader/loader.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="../js/tailwind.config.js"></script>
    <link rel="icon" type="image/png" href="../assets/suballigators_logo.png" />
    <title>Gérer les étudiants</title>
</head>

<body>

    <?php
    include_once('navbar.phtml');
    ?>
<?php

include '../php/util/conn.php';
include '../php/util/pdo_oracle.php';

// affiche trois liens vers des formations différentes

$sql = 'select distinct FormationId, FormationName from Formation where formationdeleted = 0 order by FormationId ASC';

$sqlStatement = $mysqlConnection->prepare($sql);
$sqlStatement->execute();
$all = $sqlStatement->fetchAll();


if(isset($_SESSION) && $_SESSION['initiatorIsDirector'] == 1){
    echo '<div class="my-16  text-5xl font-bold text-center">
            <h1> Gérer les étudiants </h1>
            </div><div class="gap-y-4 flex flex-col justify-center items-center">';

    for($i=0;$i<count($all);$i++){
        echo '<button class="btn btn-primary" onclick="window.location.href=\'formation.phtml?formationId=' . $all[$i]['FormationId'] . '\'">Formation ' . $all[$i]['FormationName'] . '</button><br><br>';
    }
    echo '</div>';
} else {
    $sql = 'SELECT formationid, formationname from Formation join TrainingManager using(FormationId) where InitiatorId ='.$_SESSION['initiatorId'];
    $sqlStatement = $mysqlConnection->prepare($sql);
    $sqlStatement->execute();
    $all = $sqlStatement->fetchAll();
    $formationId = $all[0]['formationid'];

    echo '<div class="my-16  text-5xl font-bold text-center">
            <h1> Gérer les étudiants </h1>
            </div> 
       ';
    echo '<button class="btn btn-primary" onclick="window.location.href=\'formation.phtml?formationId=' . $formationid . '\'">Formation ' . $all[0]['FormationName'] . '</button><br><br>';


}



include_once("footer.phtml");
?>
</body>
</html>
